pipeline {

 agent {

 label 'nodejs'

 }

 stages {

 stage ('Install Dependencies') {

 steps {

 dir ('exchange-cli') {

 sh "npm install"

 }

 }

 }

 stage ('Build') {

 stage ('Unit Tests') {

 steps {

 dir ('exchange-cli') {

 sh "npm run test:unit"

 }

 }

 }

}
